### ISSUE TITLE
Migrate Database from SQLite to SQL Server

### ISSUE THREAD

**Issue by MacheteBang** [MacheteBang/MealBot#4]
### 📝 Description
To ensure robust source control management for the SQL Server database, we will use SDK-style projects in Azure Data Studio. This will allow for better versioning, deployment tracking, and team collaboration on database changes.

---

### 👤 User Story
As a **developer**, I want to use SDK-style projects to manage our SQL Server database in source control so that we can version, review, and deploy changes reliably as part of our development workflow.

---

### ✅ Acceptance Criteria

```gherkin
Scenario: Create an SDK-style project for database management
  Given I have access to Azure Data Studio
  When I set up an SDK-style project for the SQL Server database
  Then the project should be structured and compatible with source control

Scenario: Version database changes with SDK-style project
  Given the database project is under source control
  When I make schema changes within the SDK-style project
  Then changes should be tracked and versioned in the repository

Scenario: Deploy database changes from SDK-style project
  Given I have configured an SDK-style project for SQL Server
  When I deploy changes to a SQL Server instance
  Then the deployment should be successful and reflect all source-controlled changes

Scenario: Update documentation to reflect SDK-style project setup
  Given the project setup documentation
  When I configure documentation for SDK-style project setup
  Then it should include steps for project creation, source control, and deployment

```

---

### 🛠️ Tasks
- [ ] Set up an SDK-style database project in Azure Data Studio.
- [ ] Configure the project for SQL Server and add initial schema.
- [ ] Integrate the database project with source control.
- [ ] Document procedures for making schema changes and deploying via SDK-style projects.
- [ ] Verify successful deployment of schema changes from the SDK-style project.
